### ISSUE TITLE
Small blocks don't disappear.

### ISSUE THREAD

**Issue by ichiru5555** [max1mde/FancyPhysics#1]
As you can see in the image, the small block does not disappear.
I have now deleted the plugin, but how do I get rid of the block?
I could not get rid of it with worldedit.
![スクリーンショット 2024-05-08 202715](https://github.com/max1mde/FancyPhysics/assets/101532725/6f62ed89-88dc-4461-8e3b-71ba62d52f7c)

**Comment by max1mde** [comment]
> As you can see in the image, the small block does not disappear.
> 
> I have now deleted the plugin, but how do I get rid of the block?
> 
> I could not get rid of it with worldedit.
> 
> ![スクリーンショット 2024-05-08 202715](https://github.com/max1mde/FancyPhysics/assets/101532725/6f62ed89-88dc-4461-8e3b-71ba62d52f7c)
> 
> 

This only can happen if the server crashes or the chunks where unloaded... You can remove them using this command: /kill @e[type=block_display,distance=..20]

**Comment by ichiru5555** [comment]
thank you.
