### ISSUE TITLE
Red 3D particles stuck in mid air

### ISSUE THREAD

**Issue by Romjan2000** [max1mde/FancyPhysics#2]
In my Iron Farm 
After Iron Golem death red particles not disappearing and it stuck in mid air
How can i fix it
![Screenshot (10)](https://github.com/user-attachments/assets/0f09281c-d976-445c-aeff-c493116c3c84)
![Screenshot (12)](https://github.com/user-attachments/assets/00452905-207b-4cd9-8ae5-74b194ee68a1)

**Comment by max1mde** [comment]
`/kill @e[type="block_display",distance=..20]`
